-- H2 compatible table definitions for Fee Rate Management model
-- Source data tables (loaded from JSON files in data/fee/)

CREATE TABLE IF NOT EXISTS "FEE_TOLL_STATION" (
    "ID" VARCHAR(100) NOT NULL,
    "STATIONID" VARCHAR(20) NOT NULL,
    "NAME" VARCHAR(200),
    "TYPE" INTEGER,
    "TOLLPLAZACOUNT" INTEGER,
    "NEIGHBORID" VARCHAR(100),
    "OPERATION" INTEGER,
    "RECORDGENTIME" VARCHAR(50),
    "STATIONHEX" VARCHAR(20),
    "STATUS" VARCHAR(10),
    "USESTATUS" INTEGER,
    "REALTYPE" INTEGER,
    "REGIONNAME" VARCHAR(100),
    "COUNTRYNAME" VARCHAR(100),
    "REGIONALISMCODE" VARCHAR(20),
    "REGIONLISMCODE" VARCHAR(20),
    CONSTRAINT PK_FEE_TOLL_STATION PRIMARY KEY ("STATIONID")
);

CREATE TABLE IF NOT EXISTS "FEE_TOLL_UNIT" (
    "TOLLINTERVALID" VARCHAR(20) NOT NULL,
    "TOLLINTERVALNAME" VARCHAR(200),
    "PROVINCEID" VARCHAR(10),
    "TOLLROADID" VARCHAR(20),
    "RATECODE" VARCHAR(10),
    "SECTIONID" VARCHAR(20),
    "OWNERID" VARCHAR(20),
    "STARTORGID" VARCHAR(20),
    "STARTORGTYPE" INTEGER,
    "ENDORGID" VARCHAR(20),
    "ENDORGTYPE" INTEGER,
    "STARTORGNAME" VARCHAR(200),
    "ENDORGNAME" VARCHAR(200),
    "STARTLAT" VARCHAR(20),
    "STARTLNG" VARCHAR(20),
    "ENDLAT" VARCHAR(20),
    "ENDLNG" VARCHAR(20),
    "STARTSTAKENUM" VARCHAR(20),
    "ENDSTAKENUM" VARCHAR(20),
    "ACTUALLENGTH" VARCHAR(20),
    "CHARGELENGTH" VARCHAR(20),
    "DIRECTION" INTEGER,
    "PROVINCETYPE" INTEGER,
    "OPPOSITEID" VARCHAR(20),
    "GANTRYID" VARCHAR(30),
    "GANTRYNAME" VARCHAR(200),
    "TOLLFLAG" INTEGER,
    "TOLLROADFLAG" INTEGER,
    "TOLLROADS" VARCHAR(20),
    "ROADTYPE" VARCHAR(10),
    "AREA" VARCHAR(100),
    "TOLLSECTIONID" VARCHAR(30),
    "TOLLSECTIONNAME" VARCHAR(200),
    "OWNERNAME" VARCHAR(200),
    "BINDTYPE" INTEGER,
    "ENDDATE" VARCHAR(50),
    "OPERTYPE" INTEGER,
    "VERSION" VARCHAR(20),
    "CHECKSTATUS" INTEGER,
    "LASTVER" VARCHAR(20),
    "VERUSETIME" VARCHAR(50),
    "CHECKORG" VARCHAR(100),
    "CHECKER" VARCHAR(100),
    "CHECKTIME" VARCHAR(50),
    "OPORG" VARCHAR(100),
    "OPER" VARCHAR(100),
    "OPTIME" VARCHAR(50),
    "REMARKS" VARCHAR(1000),
    "SPARE1" VARCHAR(1000),
    "SPARE2" VARCHAR(1000),
    "SPARE3" VARCHAR(1000),
    CONSTRAINT PK_FEE_TOLL_UNIT PRIMARY KEY ("TOLLINTERVALID")
);

CREATE TABLE IF NOT EXISTS "FEE_BASE_RATE" (
    "ID" VARCHAR(50) NOT NULL,
    "PROVINCEID" VARCHAR(10),
    "RATECODE" VARCHAR(10),
    "RATETYPE" INTEGER,
    "RATEDESC" VARCHAR(200),
    "VC" INTEGER,
    "VCRATE" VARCHAR(20),
    "AXLE" VARCHAR(10),
    "RATIO" VARCHAR(10),
    "OPERTYPE" INTEGER,
    "VERSION" VARCHAR(20),
    "CHECKSTATUS" INTEGER,
    "LASTVER" VARCHAR(20),
    "VERUSETIME" VARCHAR(50),
    "OPORG" VARCHAR(100),
    "OPER" VARCHAR(100),
    "OPTIME" VARCHAR(50),
    "REMARKS" VARCHAR(1000),
    "SPARE1" VARCHAR(1000),
    "SPARE2" VARCHAR(1000),
    "SPARE3" VARCHAR(1000),
    "CHECKTIME" VARCHAR(50),
    "CHECKER" VARCHAR(100),
    "CHECKORG" VARCHAR(100),
    CONSTRAINT PK_FEE_BASE_RATE PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "FEE_SPECIAL_TIME_DISCOUNT" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "TOLLINTERVALID" VARCHAR(20),
    "STARTDATE" VARCHAR(50),
    "ENDDATE" VARCHAR(50),
    "STARTHOUR" INTEGER,
    "ENDHOUR" INTEGER,
    "VEHILCETYPE" VARCHAR(10),
    "CPCDISCOUNT" INTEGER,
    "ETCDISCOUNT" INTEGER,
    "FLAG" INTEGER,
    "LASTVER" VARCHAR(20),
    "VERUSETIME" VARCHAR(50),
    CONSTRAINT PK_FEE_SPECIAL_TIME_DISCOUNT PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "FEE_NO_CONTIGUITY_RULE" (
    "ID" VARCHAR(100) NOT NULL,
    "ENROADNODEID" VARCHAR(20),
    "ENROADNODETYPE" INTEGER,
    "EXROADNODEID" VARCHAR(20),
    "EXROADNODETYPE" INTEGER,
    "CONTIGUITYTYPE" INTEGER,
    "VERSION" VARCHAR(20),
    "CHECKSTATUS" INTEGER,
    "LASTVER" VARCHAR(20),
    "VERUSETIME" VARCHAR(50),
    "OPERTYPE" INTEGER,
    "OPORG" VARCHAR(100),
    "OPER" VARCHAR(100),
    "OPTIME" VARCHAR(50),
    "REMARKS" VARCHAR(1000),
    "SPARE1" VARCHAR(1000),
    "SPARE2" VARCHAR(1000),
    "SPARE3" VARCHAR(1000),
    "CHECKORG" VARCHAR(100),
    "CHECKER" VARCHAR(100),
    "CHECKTIME" VARCHAR(50),
    CONSTRAINT PK_FEE_NO_CONTIGUITY_RULE PRIMARY KEY ("ID")
);

-- Pipeline output tables

CREATE TABLE IF NOT EXISTS "FEE_CONTIGUITY" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "EN_ROAD_NODE_ID" VARCHAR(20),
    "EN_ROAD_NODE_TYPE" INTEGER,
    "EX_ROAD_NODE_ID" VARCHAR(20),
    "EX_ROAD_NODE_TYPE" INTEGER,
    "MILES" INTEGER DEFAULT 0,
    "CHARGE_MILES" INTEGER DEFAULT 0,
    "INVALID" BOOLEAN DEFAULT FALSE,
    "RULE_ID" VARCHAR(10),
    "LASTVER" VARCHAR(20),
    CONSTRAINT PK_FEE_CONTIGUITY PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "FEE_PROVINCE_RATE_PARAM" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "TOLL_INTERVAL_ID" VARCHAR(20),
    "VEHICLE_TYPE" INTEGER,
    "FEE" INTEGER DEFAULT 0,
    "MFEE" INTEGER DEFAULT 0,
    "EFEE" INTEGER DEFAULT 0,
    "RATE_SOURCE" VARCHAR(20),
    "LASTVER" VARCHAR(20),
    CONSTRAINT PK_FEE_PROVINCE_RATE_PARAM PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "FEE_MINIMUM_FEE_PATH" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "EN_STATION_ID" VARCHAR(20),
    "EX_STATION_ID" VARCHAR(20),
    "VEHICLE_TYPE" INTEGER,
    "TOLL_INTERVALS_GROUP" VARCHAR(2000),
    "CHARGEFEE_GROUP" VARCHAR(2000),
    "CHARGEFEE95_GROUP" VARCHAR(2000),
    "TOTAL_FEE" INTEGER DEFAULT 0,
    "TOTAL_FEE95" INTEGER DEFAULT 0,
    "TOTAL_MILEAGE" INTEGER DEFAULT 0,
    "VALIDATION_FAILED" BOOLEAN DEFAULT FALSE,
    "LASTVER" VARCHAR(20),
    CONSTRAINT PK_FEE_MINIMUM_FEE_PATH PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "FEE_VALIDATION_ERROR" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "PATH_ID" BIGINT,
    "RULE_ID" VARCHAR(10),
    "MESSAGE" VARCHAR(2000),
    CONSTRAINT PK_FEE_VALIDATION_ERROR PRIMARY KEY ("ID")
);
