CREATE TABLE "CLEAR"."TBL_EXCLEARRESULTETC" 
   (	"CROPID" NUMBER(*,0) NOT NULL ENABLE, 
	"TOLLSECTIONID" VARCHAR2(11) NOT NULL ENABLE, 
	"TOLLINTERVALID" VARCHAR2(16) NOT NULL ENABLE, 
	"TOLLSTATION" VARCHAR2(14) NOT NULL ENABLE, 
	"VEHICLETYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"PAYTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"PAYCARDTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"PROVINCETYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"LDATE" DATE NOT NULL ENABLE, 
	"NATIONCLEARDATE" DATE NOT NULL ENABLE, 
	"NATIONSPLITDATE" DATE NOT NULL ENABLE, 
	"CLEARDATE" DATE NOT NULL ENABLE, 
	"MULTIPROVINCE" NUMBER(*,0) NOT NULL ENABLE, 
	"MODIFYFLAG" NUMBER(*,0) NOT NULL ENABLE, 
	"ROADTYPE" NUMBER NOT NULL ENABLE, 
	"BUSIBATCH" VARCHAR2(56) NOT NULL ENABLE, 
	"UNIONPAYTYPE" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"CLEARTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"ISSUERID" VARCHAR2(6) NOT NULL ENABLE, 
	"TOLLPROVINCEID" VARCHAR2(6) NOT NULL ENABLE, 
	"SERPROVINCEID" VARCHAR2(6) NOT NULL ENABLE, 
	"TOLLCROPID" NUMBER(*,0) NOT NULL ENABLE, 
	"SECTIONID" VARCHAR2(11) NOT NULL ENABLE, 
	"AMOUNT" NUMBER NOT NULL ENABLE, 
	"DISCOUNTAMOUNT" NUMBER NOT NULL ENABLE, 
	"CHARGEAMOUNT" NUMBER NOT NULL ENABLE, 
	"REPORTFLAG" NUMBER(*,0) NOT NULL ENABLE, 
	"LASTTIME" DATE NOT NULL ENABLE, 
	"EXTOLLSTATION" VARCHAR2(7), 
	"SPLITCOUNT" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_EXCLEARRESULTETC" PRIMARY KEY ("CLEARDATE", "CROPID", "TOLLSECTIONID", "TOLLINTERVALID", "TOLLSTATION", "VEHICLETYPE", "PAYTYPE", "PAYCARDTYPE", "PROVINCETYPE", "LDATE", "NATIONCLEARDATE", "NATIONSPLITDATE", "MULTIPROVINCE", "MODIFYFLAG", "ROADTYPE", "BUSIBATCH", "UNIONPAYTYPE", "CLEARTYPE", "ISSUERID", "TOLLPROVINCEID", "SERPROVINCEID")
);



CREATE TABLE "CLEAR"."TBL_EXCLEARRESULTCASH" 
   (	"CROPID" NUMBER(*,0) NOT NULL ENABLE, 
	"TOLLSECTIONID" VARCHAR2(11) NOT NULL ENABLE, 
	"TOLLINTERVALID" VARCHAR2(16) NOT NULL ENABLE, 
	"TOLLSTATION" VARCHAR2(14) NOT NULL ENABLE, 
	"VEHICLETYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"PAYTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"PAYCARDTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"PROVINCETYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"LDATE" DATE NOT NULL ENABLE, 
	"NATIONCLEARDATE" DATE NOT NULL ENABLE, 
	"NATIONSPLITDATE" DATE NOT NULL ENABLE, 
	"CLEARDATE" DATE NOT NULL ENABLE, 
	"MULTIPROVINCE" NUMBER(*,0) NOT NULL ENABLE, 
	"MODIFYFLAG" NUMBER(*,0) NOT NULL ENABLE, 
	"ROADTYPE" NUMBER NOT NULL ENABLE, 
	"BUSIBATCH" VARCHAR2(56) NOT NULL ENABLE, 
	"UNIONPAYTYPE" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"CLEARTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"ISSUERID" VARCHAR2(6) DEFAULT 0 NOT NULL ENABLE, 
	"TOLLPROVINCEID" VARCHAR2(6) NOT NULL ENABLE, 
	"SERPROVINCEID" VARCHAR2(6) NOT NULL ENABLE, 
	"TOLLCROPID" NUMBER(*,0) NOT NULL ENABLE, 
	"SECTIONID" VARCHAR2(11) NOT NULL ENABLE, 
	"AMOUNT" NUMBER NOT NULL ENABLE, 
	"DISCOUNTAMOUNT" NUMBER NOT NULL ENABLE, 
	"CHARGEAMOUNT" NUMBER NOT NULL ENABLE, 
	"REPORTFLAG" NUMBER(*,0) NOT NULL ENABLE, 
	"LASTTIME" DATE NOT NULL ENABLE, 
	"EXTOLLSTATION" VARCHAR2(7), 
	"SPLITCOUNT" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_EXCLEARRESULTCASH" PRIMARY KEY ("CLEARDATE", "CROPID", "TOLLSECTIONID", "TOLLINTERVALID", "TOLLSTATION", "VEHICLETYPE", "PAYTYPE", "PAYCARDTYPE", "PROVINCETYPE", "LDATE", "NATIONCLEARDATE", "NATIONSPLITDATE", "MULTIPROVINCE", "MODIFYFLAG", "ROADTYPE", "BUSIBATCH", "UNIONPAYTYPE", "CLEARTYPE", "ISSUERID", "TOLLPROVINCEID", "SERPROVINCEID")
);


-- CLEAR.TBL_MANAGESPLITSUM definition

CREATE TABLE "CLEAR"."TBL_MANAGESPLITSUM" 
   (	"CLEARDATE" DATE NOT NULL ENABLE, 
	"LDATE" DATE, 
	"SPLITORG" VARCHAR2(20) NOT NULL ENABLE, 
	"ORGTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"PAYCARDTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"MONEYFLAG" NUMBER(*,0) NOT NULL ENABLE, 
	"CASHSPLITMONEY" NUMBER, 
	"CASHOPSPLITMONEY" NUMBER, 
	"CASHTOLLMONEY" NUMBER, 
	"CASHOPTOLLMONEY" NUMBER, 
	"OTHERSPLITMONEY" NUMBER, 
	"OTHEROPSPLITMONEY" NUMBER, 
	"OTHERTOLLMONEY" NUMBER, 
	"OTHEROPTOLLMONEY" NUMBER, 
	"UNIONSPLITMONEY" NUMBER, 
	"UNIONOPSPLITMONEY" NUMBER, 
	"UNIONTOLLMONEY" NUMBER, 
	"UNIONOPTOLLMONEY" NUMBER, 
	"ETCSPLITMONEY" NUMBER, 
	"ETCOPSPLITMONEY" NUMBER, 
	"ETCTOLLMONEY" NUMBER, 
	"ETCOPTOLLMONEY" NUMBER, 
	"ALIPAYSPLITMONEY" NUMBER, 
	"ALIPAYOPSPLITMONEY" NUMBER, 
	"ALIPAYTOLLMONEY" NUMBER, 
	"ALIPAYOPTOLLMONEY" NUMBER, 
	"WEPAYSPLITMONEY" NUMBER, 
	"WEPAYOPSPLITMONEY" NUMBER, 
	"WEPAYTOLLMONEY" NUMBER, 
	"WEPAYOPTOLLMONEY" NUMBER, 
	"GENTIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CORP" VARCHAR2(6) NOT NULL ENABLE, 
	"ROAD" VARCHAR2(6) NOT NULL ENABLE, 
	"CASHRETURNMONEY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"OTHERRETURNMONEY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"UNIONRETURNMONEY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"ETCRETURNMONEY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"ALIPAYRETURNMONEY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"WEPAYRETURNMONEY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_TBL_MANAGESPLITSUM" PRIMARY KEY ("CLEARDATE", "SPLITORG", "PAYCARDTYPE", "MONEYFLAG", "ROAD", "CORP")
);



-- CLEAR.TBL_GBSECTIONDIC definition

CREATE TABLE "CLEAR"."TBL_GBSECTIONDIC" 
   (	"ID" CHAR(11) NOT NULL ENABLE, 
	"ROADID" VARCHAR2(12) NOT NULL ENABLE, 
	"NAME" VARCHAR2(150) NOT NULL ENABLE, 
	"SECTIONOWNERID" CHAR(7) NOT NULL ENABLE, 
	"TYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"LENGTH" NUMBER(*,0) NOT NULL ENABLE, 
	"STARTSTAKENUM" VARCHAR2(20) NOT NULL ENABLE, 
	"STARTLAT" VARCHAR2(20) NOT NULL ENABLE, 
	"STARTLNG" VARCHAR2(20) NOT NULL ENABLE, 
	"ENDSTAKENUM" VARCHAR2(20) NOT NULL ENABLE, 
	"ENDLAT" VARCHAR2(20) NOT NULL ENABLE, 
	"ENDLNG" VARCHAR2(20) NOT NULL ENABLE, 
	"TAX" NUMBER(*,0) NOT NULL ENABLE, 
	"TAXRATE" NUMBER(16,2) NOT NULL ENABLE, 
	"CHARGETYPE" NUMBER(*,0) NOT NULL ENABLE, 
	"TOLLROADS" VARCHAR2(150) NOT NULL ENABLE, 
	"BUILTTIME" DATE NOT NULL ENABLE, 
	"STARTTIME" DATE NOT NULL ENABLE, 
	"ENDTIME" DATE NOT NULL ENABLE, 
	"OPERATION" NUMBER(*,0) NOT NULL ENABLE, 
	"RECORDGENTIME" DATE, 
	"STATUS" CHAR(1) DEFAULT '0', 
	"BATCHFILENAME" VARCHAR2(128), 
	"RESPONSECODE" NUMBER(*,0) DEFAULT 0, 
	"RESPONSEINFO" VARCHAR2(1024), 
	"RECEIVETIME" DATE, 
	"PROTIME" DATE, 
	"NEXTTAXRATE" NUMBER(16,2), 
	"NEXTRATEDATE" DATE, 
	"SECTIONLEVEL" NUMBER(*,0), 
	"ONLINETYPE" NUMBER(*,0), 
	 CONSTRAINT "PK_TBL_GBSECTIONDIC" PRIMARY KEY ("ID")
);



CREATE TABLE "HIGHLINK"."TBL_PATH" 
   (	"ID" VARCHAR2(1000) NOT NULL ENABLE, 
	"PASSID" VARCHAR2(1000), 
	"PLATENUM" VARCHAR2(1000), 
	"PLATECOLOR" NUMBER(10,0), 
	"ENTIME" VARCHAR2(1000), 
	"EXTIME" VARCHAR2(1000), 
	"ENTOLLLANEID" VARCHAR2(1000), 
	"EXTOLLLANEID" VARCHAR2(1000), 
	"ENTOLLSTATIONID" VARCHAR2(1000), 
	"EXTOLLSTATIONID" VARCHAR2(1000),
    "EXVEHICLETYPE" NUMBER(10,0),
	"PAYTYPE" NUMBER(10,0),
	"PAYCARDTYPE" NUMBER(10,0),
	"LDATE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  


  -- HIGHLINK.TBL_SPLITDETAIL definition

CREATE TABLE "HIGHLINK"."TBL_SPLITDETAIL" 
   (	"pass_id" VARCHAR2(1000) NOT NULL ENABLE, 
	"transaction_id" VARCHAR2(1000), 
	"interval_id" VARCHAR2(1000), 
	"toll_interval_fee" VARCHAR2(1000), 
	"toll_interval_pay_fee" VARCHAR2(1000), 
	"toll_interval_discount_fee" VARCHAR2(1000), 
	"split_flag" NUMBER(10,0), 
	"pro_split_time" VARCHAR2(1000), 
	"pro_split_type" NUMBER(10,0), 
	"split_remark" VARCHAR2(1000),
    "ex_toll_station_id" VARCHAR2(1000),
    "ex_vehicle_type" NUMBER(10,0),
    "pay_type" NUMBER(10,0),
    "pay_card_type" NUMBER(10,0),
    "l_date" VARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

